### obtener todos los pets
GET http://localhost:3000/api/pets


### obtener un pet
GET http://localhost:3000/api/pets/1

### crear un nuevo pet
POST http://localhost:3000/api/pets
Content-Type: application/json

{
  "name": "Alegria",
  "birthday": "2010/08/04",
  "description": "blanca",
  "user_id" : 1,
  "specie_id": 1
}

### modificar un pet (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/pets/2
Content-Type: application/json

{
  "name": "Alegria",
  "birthday": "2010/08/04",
  "description": "blanca pequeña",
  "user_id" : 1,
  "specie_id": 1
}

### modificar un pet (PATCH - recurso parcial)
PATCH http://localhost:3000/api/pets/1
Content-Type: application/json

{
  "name": "Billy",
  "birthday": "2019/10/15",
  "description": "fat",
  "user_id" : 1,
  "specie_id": 1
}

### borrar un pet
DELETE http://localhost:3000/api/pets/a02b91bc-3769-4221-beb1-d7a3aeba7dad